// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type InformationInput struct {
	Name           string `json:"name"`
	OnCampus       bool   `json:"onCampus"`
	Building       string `json:"building"`
	Address        string `json:"address"`
	OnCampusFuture bool   `json:"onCampusFuture"`
}

type StorageItemQuantitiesInput struct {
	Quantities []*StorageItemQuantityInput `json:"quantities"`
}

type StorageItemQuantityInput struct {
	ItemID   int `json:"itemID"`
	Quantity int `json:"quantity"`
}
