// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type InformationInput struct {
	Name           string `json:"name"`
	OnCampus       bool   `json:"onCampus"`
	Building       string `json:"building"`
	Address        string `json:"address"`
	OnCampusFuture bool   `json:"onCampusFuture"`
}

type Me struct {
	Email string `json:"email"`
	Name  string `json:"name"`
	Stage int    `json:"stage"`
}
